module SinKing

mutable struct IZStates{T <: AbstractFloat}
    iz_u::T
    iz_v::T
    g_ampa::T
    g_nmda::T
    g_gaba_a::T
    g_gaba_b::T
    mrkrm_r::T
    mrkrm_w::T
end

struct IZParams{T <: AbstractFloat}
    a::T
    b::T
    mrkrm_d::T
    mrkrm_f::T
    mrkrm_u::T
end

abstract type Donor end # T::generated by agent, to be processed for sending
abstract type Acceptor end # T::processed as what agent accepts

struct TimedTransmitter
    time
    dosage
end

struct IZNeuron{T <: AbstractFloat}
    states::IZStates{T}
    params::IZParams{T}
    donors::Vector{Donor}
    Acceptor::Vector{Acceptor}
end


function evolve(states::IZStates, params::IZParams, )



end # module
