module Types

abstract type AgentStates{T <: AbstractFloat} end
abstract type Agent{S <: AgentStates} end
abstract type Donor end # T::generated by agent, to be processed for sending. should change as "to be put to channel"
abstract type Acceptor end # T::processed as what agent accepts. should be change as "taken from channel"

end
